sudo: required
language: generic
services:
    - docker

# before_install:
#     - docker build -t hnaseem/react-test -f ./client/Dockerfile.dev ./client

# script:
#     - docker run -e CI=true hnaseem/react-test npm test

after_success:
    - docker build -t hdawg5000/multi-client ./client
    - docker build -t hdawg5000/multi-nginx ./nginx
    - docker build -t hdawg5000/multi-server ./server
    - docker build -t hdawg5000/multi-worker ./worker

    # Log in to Docker CLI
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

    # Take images and push them to Docker Hub
    - docker push hdawg5000/multi-client
    - docker push hdawg5000/multi-nginx
    - docker push hdawg5000/multi-server
    - docker push hdawg5000/multi-worker